name: Go package

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./services

  integration-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          go get -u github.com/gin-gonic/gin

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./handlers

  performance-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg
          key: ${{ runner.os }}-go-pkg-${{ hashFiles('**/go.mod') }}
      - uses: actions/cache@v3
        with:
          path: ~/go/bin/benchstat
          key: ${{ runner.os }}-benchstat
      - uses: actions/cache@v3
        with:
          path: |
            bench-master.txt
          # Using base sha for PR or new commit hash for master/main push in benchmark result key.
          key: ${{ runner.os }}-bench-${{ (github.event.pull_request.base.sha != github.event.after) && github.event.pull_request.base.sha || github.event.after }}
      - name: Benchmark
        run: REF_NAME=${GITHUB_REF##*/} make bench
      
    