name: Go package

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./services

  integration-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          go get -u github.com/gin-gonic/gin

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./handlers

  performance-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest  

      - name: Run benchmarks (base)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          go test -bench . -benchmem ./... > base.txt
          git add base.txt
          git commit -m "Update benchmark results"
          git push
  
      - name: Run benchmarks (current)
        run: go test -bench . -benchmem ./... > current.txt
  
      - name: Checkout main branch to get base benchmarks
        run: |
          git fetch origin main:localmain
          git checkout localmain
          git checkout ${{ github.sha }} -- current.txt
  
      - name: Compare benchmarks
        run: |
          benchstat base.txt current.txt > comparison.txt
          cat comparison.txt
      
    